World:
  TimeBetweenTicks: 10

  Path:
    PotionEffect: "SPEED"
    EffectLevel: 1
    Blocks:
      - "GRASS_PATH"

  Race:
    Vampire:
      BurnThreshold: 14

Combat:
  HolyStarBonus: 2

  PvP:
    DmgModifier: 1.5
    ResistanceModifier: 0.5

  PvE:
    DmgModifier: 1.5
    MobList:
      - "ZOMBIE"
      - "SKELETON"

RaceDefinitions:
  Races:
    - Human:
        BaseHealth: 20
        BaseMovementSpeed: 4

    - Vampire:
        BaseHealth: 10
        BaseMovementSpeed: 6

