name: EvolveRaces
version: ${project.version}
main: me.anoninsnap.evolveraces.EvolveRaces
api-version: 1.16
authors: [ anonisnap ]
description: A Plugin, adding different Races, each with special effects and abilities. Specifically designed for the EvolveMC Minecraft Server
