name: EvolveRaces
version: ${project.version}
main: me.anoninsnap.evolveraces.EvolveRaces
api-version: 1.16
authors: [ anonisnap ]
description: A Plugin, adding different Races, each with special effects and abilities. Specifically designed for the EvolveMC Minecraft Server
commands:
  setRace:
    description: Set the Race of a player
    usage: /<command> [player] <race>

  getRace:
    description: Get the Race of a player
    usage: /<command> [player]

  consoleLog:
    description: Change if the plugin should show the Debugging Logs in Console
    usage: /<command> <true/false>

  allRaces:
    description: